# -*- coding: utf-8 -*-
"""python_class_1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11XcsQpVO-Ae__cxhXOIAK3A-fOLLdEFd

Shortcuts:
1. Command + ? - Comment Out
2. Shift + Return/Enter - Run
3. Command + Z - Undo
4. Command + X - Cut
5. Command + C - Copy
6. Command + V - Paste 
7. Command + S - Save
"""

#Division

#Normal Division
print("Normal Division: ", 10/3) 

#Floor Division
print("Floor Division: ", 10//3)

#Remainder 

print("Remainder: ")
10%3

#Exponent

print("Exponent: ")
10**2

#Variable 

print("Variable: ")
name= "Md Affan"

#my_var= value